#!/bin/bash

VERS=`git tag`
LINKS=""
for one in $VERS; do
    LINKS="$LINKS<p><a href=\"./$one\">$one</a></p>"
done

TEST=`cat << _EOF_ 
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>index</title>
    </head>
    <body>
        <style>* { margin: 0; padding: 0}</style>
        $LINKS
    </body>
</html>
_EOF_`

echo $TEST
